### ISSUE TITLE
About fonts

### ISSUE THREAD

**Issue by hurumori** [leaningtech/cheerpj-applet-runner#11]
The other day,
thank you very much for giving me advice.
https://github.com/leaningtech/cheerpj-appletrunner/issues/10

Due to security restrictions of javascript,
I understood that I can not load fonts installed on OS into applet.

I am using Japanese fonts.
Currently, all Japanese fonts are displayed as "□" blank.

![181109-131441](https://user-images.githubusercontent.com/43722233/48262550-41690980-e466-11e8-84c2-b34193dd90ee.jpg)

In java, if you place fonts in <java_path> / lib / fonts,
I can load that font into the applet.

In a similar way,
To the same server on which jar resides, or to any server,
Place the font file,
Is it possible to read the font file?

Alternatively,
· Use fonts such as 'sans-serif', 'serif' and 'monospace' selected by the browser
· Use web fonts
· Use a script like 'document.paintbbs.???="fontname"'
etc..
Is it possible to send fonts to the font tool?

If it is out of the category of "cheerpj" or impossible,
I am sorry to be a rude question.

If there is a way to use Japanese fonts, I am very happy.

**Comment by alexp-sssup** [comment]
In the future we will expand the set of supported fonts, but we don't have a defined timeline right now. I am sorry for the inconvenience.

**Comment by hurumori** [comment]
I had no knowledge to judge whether it was possible or impossible, and I was in trouble.
Likewise, Thank you for answering me.

**Comment by midorism64** [comment]
Many applications cannot render multibyte characters in case they're not embedded (and perhaps their font name is specified).

Example:
http://www.shiftup.net/java11/PonQ11/index.html

We would appreciate if you could add substitution fonts to cheerpj for such applications. Thank you.

**Comment by alexp-sssup** [comment]
International font rendering is now supported out of the box in version `2024.10` of the CheerpJ Applet Runner extension. This new version is based on CheerpJ 3.0 architecture and brings many improvements to performance and robustness.
