### ISSUE TITLE
Website requires java plugin

### ISSUE THREAD

**Issue by JdHora** [leaningtech/cheerpj-applet-runner#58]
I have this error . The website doesn't work properly even though I have already installed java.

![image](https://user-images.githubusercontent.com/116576594/197557344-885fea52-b02b-4d76-abc0-f3d70d825f6c.png)

What should I do to get past it?

Thanks.

**Comment by JdHora** [comment]
Sorry. I'd tried it but not work!

**Comment by marsicplusplus** [comment]
Could you open the dev tool console after clicking on the extension (Three dots on the right -> More Tools -> Developer Tools -> Console), and send us a screenshot of it?

**Comment by JdHora** [comment]
Google Chrome:

![image](https://user-images.githubusercontent.com/116576594/197574937-ca8d7c47-9f3b-4cbe-a3d0-491b2777eb43.png)

Microsoft Edge Chromium:

![image](https://user-images.githubusercontent.com/116576594/197575777-d8c0197e-aaee-4912-b0fd-18d77b25b978.png)

**Comment by JdHora** [comment]
Google Chrome:
![image](https://user-images.githubusercontent.com/116576594/197576499-69c436c0-6f90-4b7f-9199-24313531beea.png)

Microsoft Edge:
![image](https://user-images.githubusercontent.com/116576594/197577178-ab10bac9-f1ec-4184-82c0-7ade522fc8c7.png)

**Comment by JdHora** [comment]
![image](https://user-images.githubusercontent.com/116576594/197581648-4fdc27b2-80fe-44ea-b989-0191280e8824.png)

**Comment by marsicplusplus** [comment]
Could you scroll down and show me the final part of the output? Or copy paste the output from the console

**Comment by alexp-sssup** [comment]
Closing due to lack of information, since the website is not publicly accessible
