### ISSUE TITLE
How to add a certificate to the keystore (cacerts file)

### ISSUE THREAD

**Issue by kaising** [leaningtech/cheerpj-applet-runner#63]
Hi All,
I could not find a way to add (or remove) a certificate from the keystore as the 'keytool' seems to not exists in cheerPj applet runner...
Am i wrong?
Solution?
regards,

**Comment by alexp-sssup** [comment]
The certificates are stores in the cloud runtime file system, so it's not possible to change them locally. This could be achieved with a self-hosted runtime or extension, that is commercially available.

Depending on your specific need that might not be required though. For HTTPS connections in particular the browser APIs are used directly, so you will need to configure certificates at the browser or OS level.

**Comment by alexp-sssup** [comment]
Closing, allowing users to add certificates (or otherwise modify the runtime files) is out-of-scope for the CheerpJ Applet Runner extension. It can be achieved with a commercial self-hosted license
