### ISSUE TITLE
Doesn't seem to be working on this website

### ISSUE THREAD

**Issue by junsukim1994** [leaningtech/cheerpj-applet-runner#65]
https://mathcs.org/analysis/reals/numseq/answers/convdiv1.html

I've tried uninstalling it and installing it again. I quit Chrome and restarted it to see if the extension works, but it didn't. How can I see the Java programs on that website?

**Comment by alexp-sssup** [comment]
This website references code on a 3rd party website, see screenshot.
![image](https://github.com/leaningtech/cheerpj-applet-runner/assets/191061/7c8251e2-81e9-4ab4-a328-b18b61a45321)

This 3rd party website seems to be down or inaccessible, so the applet cannot load. There is nothing that CheerpJ can do about it.
