### ISSUE TITLE
Applet Support on IE

### ISSUE THREAD

**Issue by ssporwal** [leaningtech/cheerpj-applet-runner#66]
Do you have applet support extension for IE browser?

**Comment by alexp-sssup** [comment]
No, there is no support for Internet Explorer in the CheerpJ Applet Runner extension. I am not even sure if extension mechanisms were supported in IE at all.

The legacy version of CheerpJ itself (2.3) does support Internet Explorer, although we have dropped support completely as part of the new 3.0 release.

One of the purposes for CheeerpJ and CheerpJ Applet Runner is to remove the need for the obsolete Internet Explorer browser. The applets should just work on any modern browser.

Can you elaborate on why is IE a requirement for you?

**Comment by alexp-sssup** [comment]
There is currently no extension for IE. I would recommend to try if Chrome works for your application, sometimes IE emulation is not strictly required and Chrome works well enough.

For further discussion I would like to recommend joining our Discord: https://discord.gg/X9ruPkchM5
